Audit Item L03
endaoment/endaoment-contracts pull request #47
Opened 2020-07-31 19:10 UTC by rheeger

closes #24

2020-07-31 20:19 UTC, CantelopePeel requested changes

2020-07-31 20:19 UTC, CantelopePeel commented on contracts/Org.sol
> +     * @param tokenAddress Address of desired token to query for balance
Add @returns

2020-07-31 20:19 UTC, CantelopePeel commented on contracts/Org.sol
> +     * @notice Retrieves Count of Claims Made
Ditto

2020-07-31 20:19 UTC, CantelopePeel commented on contracts/Org.sol
> +     * @param providedWallet Wallet address that will serve as destination for withdrawl
s/withdrawl/withdrawal

2020-08-01 18:11 UTC, rheeger commented on contracts/Org.sol
> +     * @param providedWallet Wallet address that will serve as destination for withdrawl
fixed

2020-08-01 18:14 UTC, rheeger commented on contracts/Org.sol
> +     * @notice Retrieves Count of Claims Made
fixed

2020-08-01 18:14 UTC, rheeger commented on contracts/Org.sol
> +     * @param tokenAddress Address of desired token to query for balance
fixed

2020-08-01 18:21 UTC, CantelopePeel approved these changes
LGTM

2020-08-01 18:24 UTC, merged